const products = {
  image: {
    width: "180",
    url: "https://media.kohlsimg.com/is/image/kohls/6235047?wid=180&hei=180&op_sharpen=1",
    height: "180",
  },
  availableColr: ["Ynk Navy"],
  sephoraProduct: false,
  rating: {
    count: null,
    avgRating: null,
  },
  valueAddedIcons: [],
  prodType: "product",
  ypEligible: false,
  sponsoredData: null,
  valueAddedBadges: null,
  isBossAvailable: false,
  productTitle: "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
  isAvailableforShip: true,
  seoURL:
    "/product/prd-6235047/womens-new-era-navy-new-york-yankees-sherpa-full-zip-jacket.jsp",
  webID: "6235047",
  couponEligible: false,
  isVGC: false,
  variations: "Size",
  storeNumbers: [
    {
      value: "873",
    },
  ],
  swatchImages: [],
  displayColor: ["Ynk Navy"],
  prices: [
    {
      isCurrentPrice: true,
      salePriceType: null,
      isSuppressed: false,
      salePrice: {
        minPrice: 59.99,
        maxPrice: null,
      },
      salePriceStatus: "sale",
      regularPrice: {
        minPrice: 74.99,
        maxPrice: null,
      },
      regularPriceType: "Regular",
      displayEndDateTime: "2023/04/08 21:38:49 -0700",
      purchaseBegDateTime: "2023/04/07 07:10:50 -0700",
      purchaseEndDateTime: "2023/04/08 21:38:49 -0700",
      priceCode: "Normal",
      suppressedPricingText: null,
      promotions: {
        tieredPrice: [],
        bogo: [],
        group: [],
      },
      displayBegDateTime: "2023/04/07 07:10:50 -0700",
      promotion: null,
      statusCode: "20",
      isPriceInstore: false,
    },
  ],
  boosted: false,
  altImageUrl: null,
  isAvailableforPickUp: false,
};

const details = {
  payload: {
    products: [
      {
        description: {
          shortDescription:
            "Stay warm and cozy in this New York Yankees full-zip jacket from New Era. It features super-soft Sherpa fabric with the New York Yankees logo displayed on the front and an adjustable hood for extra heat. Roomy pockets also make sliding in your hands or essentials easy.",
          longDescription:
            "<p>Stay warm and cozy in this New York Yankees full-zip jacket from New Era. It features super-soft Sherpa fabric with the New York Yankees logo displayed on the front and an adjustable hood for extra heat. Roomy pockets also make sliding in your hands or essentials easy.</p></br><p>PRODUCT FEATURES</p><ul><li>Full-zip</li><li>Officially licensed</li><li>Embroidered graphics</li><li>Imported</li><li>Brand: New Era</li><li>Long sleeve</li><li>Hood with drawstring</li><li>Midweight jacket suitable for moderate temperatures</li><li>Sherpa fabric</li><li>Two front pockets</li><li>Machine wash, tumble dry low</li><li>Material: 100% Polyester</li></ul>",
        },
        webID: "6235047",
        price: {
          regularPriceType: "Regular",
          salePriceStatus: "Sale",
          isSuppressed: false,
          regularPrice: {
            minPrice: 74.99,
            maxPrice: null,
          },
          salePrice: {
            minPrice: 59.99,
            maxPrice: null,
          },
          yourPriceInfo: {
            yourPrice: null,
            yourPriceSavings: null,
            offersIncludedInYourPrice: [],
            offersEligibleForYourPrice: [],
            appliedOffers: [],
            saveMoreOffers: [],
          },
          promotion: {
            tieredPrice: null,
            group: null,
            bogo: null,
          },
          percentageOff: null,
          suppressedPricingText: null,
          loyalty: {
            pointsEarned: {
              min: null,
              max: null,
            },
            loyaltyExclusions: null,
          },
          kohlsCash: {
            kcEarned: {
              min: 10.0,
              max: null,
            },
            kcEarningPeriod: {
              startDate: "2023-03-30 00:00:00.000",
              endDate: "2023-04-08 23:59:59.999",
            },
            kcRedemptionPeriod: {
              startDate: "2023-04-09 00:00:00.000",
              endDate: "2023-04-16 00:00:00.000",
            },
            kcExclusions:
              "https://www.kohls.com/ecom/Kcash/EarnKohlsCash_20230330_20230408.html",
          },
          lowestApplicablePrice: {
            minPrice: 59.99,
            maxPrice: null,
          },
        },
        images: [
          {
            url: "https://media.kohlsimg.com/is/image/kohls/6235047?wid=350&hei=350&op_sharpen=1",
            height: "350",
            width: "350",
            altText:
              "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
          },
        ],
        brand: "New Era",
        brandSeoUrl:
          "/catalog/womens-new-era.jsp?CN=Gender:Womens+Brand:New%20Era",
        swatchImages: [],
        productStatus: "In Stock",
        productTitle:
          "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
        productURL: "https://www.kohls.com/product/prd-6235047/product.jsp",
        avgRating: "0.0",
        ratingCount: 0,
        recommendedPercentage: 0,
        videos: [],
        surcharges: [],
        bestSeller: false,
        topRated: false,
        valueAddedIcons: [],
        productOffers: [],
        styleGuide: {
          productGuideText: "Tailgate Guide",
        },
        metaInfo: [
          {
            metaTitle: "Kohls",
            metaDescription:
              "Stay warm and cozy in this New York Yankees full-zip jacket from New Era. It features super-soft Sherpa fabric with the New York Yankees logo displayed on the front and an adjustable hood for extra heat. Roomy pockets also make sliding in your hands or essentials easy.",
            metaKeywords: null,
          },
        ],
        seoURL:
          "/product/prd-6235047/womens-new-era-navy-new-york-yankees-sherpa-full-zip-jacket.jsp",
        rebate: {
          shortDescription: null,
          longDescription: null,
          rebateURL: null,
        },
        exclusions: {
          shortDescription:
            "This product is not eligible for coupons. However, you are able to earn and redeem Kohl’s Cash® and Kohl's Rewards® on this product.",
          longDescription: null,
        },
        altImages: [
          {
            url: "https://media.kohlsimg.com/is/image/kohls/6235047_ALT?wid=50&hei=50&op_sharpen=1",
            height: "50",
            width: "50",
            altText:
              "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
          },
          {
            url: "https://media.kohlsimg.com/is/image/kohls/6235047_ALT2?wid=50&hei=50&op_sharpen=1",
            height: "50",
            width: "50",
            altText:
              "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
          },
          {
            url: "https://media.kohlsimg.com/is/image/kohls/6235047_ALT3?wid=50&hei=50&op_sharpen=1",
            height: "50",
            width: "50",
            altText:
              "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
          },
        ],
        isBopusEligible: false,
        monetization: {
          brand: {
            value: "new era",
          },
          ageAppropriate: {
            value: "adult",
          },
          occasion: {
            value: "sports fan",
          },
          gender: {
            value: "womens",
          },
          sportsLeague: {
            value: "mlb",
          },
          sportsTeam: {
            value: "new york yankees",
          },
          personaCategory: null,
          personaTheme: null,
          personaSubject: null,
          personaGroupCode: null,
          adUnit: {
            value: "/clothing/tops/tops_and_tees",
          },
          silhouette: {
            value: "hoodies & sweatshirts",
          },
          ageAppropriateRange: null,
          childAgeRange: null,
          sizeRange: null,
          fit: null,
          legOpening: null,
          trend: {
            value: "no primary trend",
          },
          feature: null,
          activity: null,
          bodyType: null,
          roastsFlavors: null,
        },
        monetizationAttributes: {
          ageAppropriate: "Adult",
          gender: "Womens",
          partnership: null,
          childAgeRange: null,
          sizeRange: "Regular",
          audiences: null,
        },
        isLTLProduct: false,
        isMarketplaceItem: false,
        shippingAndReturn:
          "</ul></br>View our full return policy <a target=_blank href=https://cs.kohls.com/app/answers/detail/a_id/893/kw/returns/session/L3RpbWUvMTQwNzg2NDIxMC9zaWQvRVpFQmVHX2w%3D>here.</a></p><p>&nbsp;</p>",
        pricingDetails: null,
        preSelectedColor: null,
        preSelectedSku: "29770420",
        specialEventPriceSummary: null,
        regulatedClass: null,
        taxCode: "61000",
        isNew: false,
        defaultAccordion: "productDetails",
        productType: {
          isBuyProduct: false,
          isGetProduct: false,
          isVGC: false,
        },
        productFeatureCode: "30",
        productDetails:
          "<p>Stay warm and cozy in this New York Yankees full-zip jacket from New Era. It features super-soft Sherpa fabric with the New York Yankees logo displayed on the front and an adjustable hood for extra heat. Roomy pockets also make sliding in your hands or essentials easy.</p></br><p>PRODUCT FEATURES</p><ul><li>Full-zip</li><li>Officially licensed</li><li>Embroidered graphics</li><li>Imported</li><li>Brand: New Era</li><li>Long sleeve</li><li>Hood with drawstring</li><li>Midweight jacket suitable for moderate temperatures</li><li>Sherpa fabric</li><li>Two front pockets</li><li>Machine wash, tumble dry low</li><li>Material: 100% Polyester</li></ul>",
        sizing: null,
        ingredients: null,
        careInstructions: null,
        relatedInformation:
          '<p><a target="_blank" href="https://www.kohls.com/feature/tailgating-traditions.jsp">Tailgate Guide</a></p>',
        availableAccordions: [
          "productDetails",
          "shippingAndReturn",
          "relatedInformation",
        ],
        badges: [],
        vendorDetails: null,
        maxQuantityMessage:
          "You can only purchase 3 of this item. Please select a lower amount and try again",
        itemMaxAvailableCount: "3",
        richCopyBlock: null,
        textCopyBlock: null,
        partnership: null,
        aboutTheBrand: null,
        howToUse: null,
        skuColorDescription: null,
        dept: "917",
        allSkusAvailableOnline: false,
        isBossEligible: false,
        ypEligibility: "Eligible for Your Price",
        SKUS: [
          {
            skuCode: "29770419",
            images: [
              {
                url: "https://media.kohlsimg.com/is/image/kohls/6235047?wid=350&hei=350&op_sharpen=1",
                height: "350",
                width: "350",
                altText:
                  "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
              },
            ],
            color: "Ynk Navy",
            size: "XS",
            price: {
              isSuppressed: false,
              salePriceStatus: "Sale",
              salePrice: {
                minPrice: 59.99,
                maxPrice: null,
              },
              regularPriceType: "Regular",
              regularPrice: {
                minPrice: 74.99,
                maxPrice: null,
              },
              promotion: {
                tieredPrice: null,
                group: null,
                bogo: null,
              },
              suppressedPricingText: null,
              yourPriceInfo: {
                yourPrice: null,
                yourPriceSavings: null,
                appliedOffers: [],
                saveMoreOffers: [],
                offersIncludedInYourPrice: [],
                offersEligibleForYourPrice: [],
              },
              pointsEarned: null,
              kcEarned: 10.0,
              lowestApplicablePrice: 59.99,
            },
            availability: "Out of Stock",
            giftWrappable: false,
            specialTypeSku: "N",
            isBopusEligible: false,
            storeInfo: null,
            sortOrder: "917000000221",
            itemMaxAllowedCount: 99,
            itemMaxAvailableCount: 0,
            maxQuantityMessage:
              "You can only purchase 0 of this item. Please select a lower amount and try again",
            shippingServiceCode: "1",
            isStoreAvailable: false,
            surcharge: null,
            sizeRange: "Regular",
            finish: null,
            coverage: null,
            formulation: null,
            skinType: null,
            benefits: null,
            concerns: null,
            sustainability: null,
            skinCareType: null,
            refillable: null,
            swatchOrder: null,
            skuColorDescription: null,
            isBossEligible: false,
            UPC: {
              image: null,
              ID: "000196499077200",
            },
          },
          {
            skuCode: "29770420",
            images: [
              {
                url: "https://media.kohlsimg.com/is/image/kohls/6235047?wid=350&hei=350&op_sharpen=1",
                height: "350",
                width: "350",
                altText:
                  "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
              },
            ],
            color: "Ynk Navy",
            size: "S",
            price: {
              isSuppressed: false,
              salePriceStatus: "Sale",
              salePrice: {
                minPrice: 59.99,
                maxPrice: null,
              },
              regularPriceType: "Regular",
              regularPrice: {
                minPrice: 74.99,
                maxPrice: null,
              },
              promotion: {
                tieredPrice: null,
                group: null,
                bogo: null,
              },
              suppressedPricingText: null,
              yourPriceInfo: {
                yourPrice: null,
                yourPriceSavings: null,
                appliedOffers: [],
                saveMoreOffers: [],
                offersIncludedInYourPrice: [],
                offersEligibleForYourPrice: [],
              },
              pointsEarned: null,
              kcEarned: 10.0,
              lowestApplicablePrice: 59.99,
            },
            availability: "In Stock",
            giftWrappable: false,
            specialTypeSku: "N",
            isBopusEligible: false,
            storeInfo: null,
            sortOrder: "917000000222",
            itemMaxAllowedCount: 99,
            itemMaxAvailableCount: 3,
            maxQuantityMessage:
              "You can only purchase 3 of this item. Please select a lower amount and try again",
            shippingServiceCode: "1",
            isStoreAvailable: false,
            surcharge: null,
            sizeRange: "Regular",
            finish: null,
            coverage: null,
            formulation: null,
            skinType: null,
            benefits: null,
            concerns: null,
            sustainability: null,
            skinCareType: null,
            refillable: null,
            swatchOrder: null,
            skuColorDescription: null,
            isBossEligible: false,
            UPC: {
              image: null,
              ID: "000400297704207",
            },
          },
          {
            skuCode: "29770421",
            images: [
              {
                url: "https://media.kohlsimg.com/is/image/kohls/6235047?wid=350&hei=350&op_sharpen=1",
                height: "350",
                width: "350",
                altText:
                  "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
              },
            ],
            color: "Ynk Navy",
            size: "M",
            price: {
              isSuppressed: false,
              salePriceStatus: "Sale",
              salePrice: {
                minPrice: 59.99,
                maxPrice: null,
              },
              regularPriceType: "Regular",
              regularPrice: {
                minPrice: 74.99,
                maxPrice: null,
              },
              promotion: {
                tieredPrice: null,
                group: null,
                bogo: null,
              },
              suppressedPricingText: null,
              yourPriceInfo: {
                yourPrice: null,
                yourPriceSavings: null,
                appliedOffers: [],
                saveMoreOffers: [],
                offersIncludedInYourPrice: [],
                offersEligibleForYourPrice: [],
              },
              pointsEarned: null,
              kcEarned: 10.0,
              lowestApplicablePrice: 59.99,
            },
            availability: "In Stock",
            giftWrappable: false,
            specialTypeSku: "N",
            isBopusEligible: false,
            storeInfo: null,
            sortOrder: "917000000223",
            itemMaxAllowedCount: 99,
            itemMaxAvailableCount: 2,
            maxQuantityMessage:
              "You can only purchase 2 of this item. Please select a lower amount and try again",
            shippingServiceCode: "1",
            isStoreAvailable: false,
            surcharge: null,
            sizeRange: "Regular",
            finish: null,
            coverage: null,
            formulation: null,
            skinType: null,
            benefits: null,
            concerns: null,
            sustainability: null,
            skinCareType: null,
            refillable: null,
            swatchOrder: null,
            skuColorDescription: null,
            isBossEligible: false,
            UPC: {
              image: null,
              ID: "000400297704214",
            },
          },
          {
            skuCode: "29770422",
            images: [
              {
                url: "https://media.kohlsimg.com/is/image/kohls/6235047?wid=350&hei=350&op_sharpen=1",
                height: "350",
                width: "350",
                altText:
                  "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
              },
            ],
            color: "Ynk Navy",
            size: "L",
            price: {
              isSuppressed: false,
              salePriceStatus: "Sale",
              salePrice: {
                minPrice: 59.99,
                maxPrice: null,
              },
              regularPriceType: "Regular",
              regularPrice: {
                minPrice: 74.99,
                maxPrice: null,
              },
              promotion: {
                tieredPrice: null,
                group: null,
                bogo: null,
              },
              suppressedPricingText: null,
              yourPriceInfo: {
                yourPrice: null,
                yourPriceSavings: null,
                appliedOffers: [],
                saveMoreOffers: [],
                offersIncludedInYourPrice: [],
                offersEligibleForYourPrice: [],
              },
              pointsEarned: null,
              kcEarned: 10.0,
              lowestApplicablePrice: 59.99,
            },
            availability: "Out of Stock",
            giftWrappable: false,
            specialTypeSku: "N",
            isBopusEligible: false,
            storeInfo: null,
            sortOrder: "917000000224",
            itemMaxAllowedCount: 99,
            itemMaxAvailableCount: 0,
            maxQuantityMessage:
              "You can only purchase 0 of this item. Please select a lower amount and try again",
            shippingServiceCode: "1",
            isStoreAvailable: false,
            surcharge: null,
            sizeRange: "Regular",
            finish: null,
            coverage: null,
            formulation: null,
            skinType: null,
            benefits: null,
            concerns: null,
            sustainability: null,
            skinCareType: null,
            refillable: null,
            swatchOrder: null,
            skuColorDescription: null,
            isBossEligible: false,
            UPC: {
              image: null,
              ID: "000400297704221",
            },
          },
          {
            skuCode: "29770423",
            images: [
              {
                url: "https://media.kohlsimg.com/is/image/kohls/6235047?wid=350&hei=350&op_sharpen=1",
                height: "350",
                width: "350",
                altText:
                  "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
              },
            ],
            color: "Ynk Navy",
            size: "XL",
            price: {
              isSuppressed: false,
              salePriceStatus: "Sale",
              salePrice: {
                minPrice: 59.99,
                maxPrice: null,
              },
              regularPriceType: "Regular",
              regularPrice: {
                minPrice: 74.99,
                maxPrice: null,
              },
              promotion: {
                tieredPrice: null,
                group: null,
                bogo: null,
              },
              suppressedPricingText: null,
              yourPriceInfo: {
                yourPrice: null,
                yourPriceSavings: null,
                appliedOffers: [],
                saveMoreOffers: [],
                offersIncludedInYourPrice: [],
                offersEligibleForYourPrice: [],
              },
              pointsEarned: null,
              kcEarned: 10.0,
              lowestApplicablePrice: 59.99,
            },
            availability: "Out of Stock",
            giftWrappable: false,
            specialTypeSku: "N",
            isBopusEligible: false,
            storeInfo: null,
            sortOrder: "917000000225",
            itemMaxAllowedCount: 99,
            itemMaxAvailableCount: 0,
            maxQuantityMessage:
              "You can only purchase 0 of this item. Please select a lower amount and try again",
            shippingServiceCode: "1",
            isStoreAvailable: false,
            surcharge: null,
            sizeRange: "Regular",
            finish: null,
            coverage: null,
            formulation: null,
            skinType: null,
            benefits: null,
            concerns: null,
            sustainability: null,
            skinCareType: null,
            refillable: null,
            swatchOrder: null,
            skuColorDescription: null,
            isBossEligible: false,
            UPC: {
              image: null,
              ID: "000196499077194",
            },
          },
          {
            skuCode: "29770424",
            images: [
              {
                url: "https://media.kohlsimg.com/is/image/kohls/6235047?wid=350&hei=350&op_sharpen=1",
                height: "350",
                width: "350",
                altText:
                  "Women's New Era Navy New York Yankees Sherpa Full-Zip Jacket",
              },
            ],
            color: "Ynk Navy",
            size: "2X",
            price: {
              isSuppressed: false,
              salePriceStatus: "Sale",
              salePrice: {
                minPrice: 59.99,
                maxPrice: null,
              },
              regularPriceType: "Regular",
              regularPrice: {
                minPrice: 74.99,
                maxPrice: null,
              },
              promotion: {
                tieredPrice: null,
                group: null,
                bogo: null,
              },
              suppressedPricingText: null,
              yourPriceInfo: {
                yourPrice: null,
                yourPriceSavings: null,
                appliedOffers: [],
                saveMoreOffers: [],
                offersIncludedInYourPrice: [],
                offersEligibleForYourPrice: [],
              },
              pointsEarned: null,
              kcEarned: 10.0,
              lowestApplicablePrice: 59.99,
            },
            availability: "Out of Stock",
            giftWrappable: false,
            specialTypeSku: "N",
            isBopusEligible: false,
            storeInfo: null,
            sortOrder: "917000000571",
            itemMaxAllowedCount: 99,
            itemMaxAvailableCount: 0,
            maxQuantityMessage:
              "You can only purchase 0 of this item. Please select a lower amount and try again",
            shippingServiceCode: "1",
            isStoreAvailable: false,
            surcharge: null,
            sizeRange: "Plus",
            finish: null,
            coverage: null,
            formulation: null,
            skinType: null,
            benefits: null,
            concerns: null,
            sustainability: null,
            skinCareType: null,
            refillable: null,
            swatchOrder: null,
            skuColorDescription: null,
            isBossEligible: false,
            UPC: {
              image: null,
              ID: "000400297704245",
            },
          },
        ],
        isStoreAvailable: false,
        kcEligible: true,
        priceSet: [59.99],
        breadcrumbs: [
          {
            name: "Womens",
            seoURL: "/catalog/womens.jsp?CN=Gender:Womens",
            currentDimensionId: "Gender:Womens",
          },
          {
            name: "Clothing",
            seoURL:
              "/catalog/womens-clothing.jsp?CN=Gender:Womens+Department:Clothing",
            currentDimensionId: "Department:Clothing",
          },
          {
            name: "Tops",
            seoURL:
              "/catalog/womens-tops-clothing.jsp?CN=Gender:Womens+Category:Tops+Department:Clothing",
            currentDimensionId: "Category:Tops",
          },
          {
            name: "Tops & Tees",
            seoURL:
              "/catalog/womens-tops-tees-tops-clothing.jsp?CN=Gender:Womens+Product:Tops%20%26%20Tees+Category:Tops+Department:Clothing",
            currentDimensionId: "Product:Tops%20%26%20Tees",
          },
          {
            name: "New Era",
            seoURL:
              "/catalog/womens-new-era.jsp?CN=Gender:Womens+Brand:New%20Era",
            currentDimensionId: "Brand:New%20Era",
          },
        ],
      },
    ],
  },
  count: 1,
  limit: 1,
  offset: 1,
};
